name: hub-release-automation
on:
  workflow_dispatch:
    inputs:
      password:
        description: "A dummy input parameter"
        required: true
      name:
        description: "Name of person to be greeted"
        required: true
        default: "Pranav"
jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.6.3
      - run: mvn -version
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - run: |
          java -version
          javac -version
      - run: |
          java -version
          mvn -version
          cd packager/
          mvn clean install
          echo "-------"
          echo "-------"
          echo "Maven packages cleaned"
          cd ../
          java -cp packager/target/*:packager/lib/* io.cdap.hub.Tool build
      - run: ls

#      - run: |
#          echo "Hey there, ${{ github.event.inputs.name }}!"
#          sudo bash -f ./.github/scripts/build.sh
#        shell: bash
