name: hub-release-automation
on:
  workflow_dispatch:
    inputs:
      password:
        description: "A dummy input parameter"
        required: true
      name:
        description: "Name of person to be greeted"
        required: true
        default: "Pranav"
jobs:
  setup-and-build:
    runs-on: new-runner
    steps:
      - uses: actions/checkout@v2.3.4
      - with:
          path: hub
      - run: mvn -version
      - run: java -version
      - run: javac -version
#      - name: Setup Maven
#        run: docker pull maven:3.6.3-openjdk-8
#      - run: docker run maven:3.6.3-openjdk-8 -version
#      - name: Setup Java 8
#        run: docker pull openjdk:8-jdk
#      - run: |
#          java -version
#          javac -version
      - run: |
          cd packager/
          mvn clean install
          echo "-------"
          echo "-------"
          echo "Maven packages cleaned"
          cd ../
          java -cp packager/target/*:packager/lib/* io.cdap.hub.Tool build
      - run: ls

#      - run: |
#          echo "Hey there, ${{ github.event.inputs.name }}!"
#          sudo bash -f ./.github/scripts/build.sh
#        shell: bash
