name: fetch-missing-jar-json
on: workflow_dispatch
jobs:
  list-files:
    runs-on: new-runner
    steps:
    - uses: actions/checkout@v2.3.4
    - run: chmod +x ./.github/scripts/fetch.sh
    - run: ./.github/scripts/fetch.sh
    - id: set-matrix
      run: echo "::set-output name=matrix::${output}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-files:
    needs: list-files
    runs-on: new-runner
    strategy:
      fail-fast: false
      matrix:
        artifact: ${{ fromJSON(needs.list-files.outputs.matrix) }}
    env:
      ARTIFACT: ${{ matrix.artifact.path }}
      URL: ${{ matrix.artifact.repo.url }}
      TAG: ${{ matrix.artifact.repo.tag }}
      REPO: ${{ matrix.artifact.repo.repo }}
      OWNER: ${{ matrix.artifact.repo.owner }}
    steps:
      - run: |
          echo "$ARTIFACT";
          echo "$TAG";
          echo "$URL";
          echo "$REPO";
          echo "$OWNER";
      - uses: actions/checkout@v2.3.4
        with:
          repository: ${{ matrix.artifact.repo.checkout }}
          ref: ${{ matrix.artifact.repo.tag }}
      - run: ls
      - run: mvn clean package -DskipTests
      - run: ls
      - run: |
          cd target/
          ls