name: fetch-missing-jar-json
on: workflow_dispatch
jobs:
  list-files:
    runs-on: new-runner
    steps:
    - uses: actions/checkout@v2.3.4
    - run: chmod +x ./.github/scripts/fetch.sh
    - run: ./.github/scripts/fetch.sh
    - id: set-matrix
      run: echo "::set-output name=matrix::${output}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-files:
    needs: list-files
    runs-on: new-runner
    strategy:
      fail-fast: false
      matrix:
        artifact: ${{ fromJSON(needs.list-files.outputs.matrix) }}
    env:
      ARTIFACT: ${{ matrix.artifact.path }}
      URL: ${{ matrix.artifact.url }}
      GTAG: `echo $ARTIFACT | cut -d "/" -f 3`
      GREPO: $(echo $URL | cut -d "/" -f 4-5)
    steps:
      - run: echo "${{ matrix.artifact.path }} - ${{ matrix.artifact.url }}"
#      - run: export ARTIFACT="${{ matrix.artifact.path }}"
#      - run: export URL="${{ matrix.artifact.url }}"
#      - run: export TAG=`echo "$ARTIFACT" | cut -d "/" -f 3`
#      - run: export REPO=`echo "$URL" | cut -d "/" -f 4-5`
      - run: |
          echo "$ARTIFACT";
          echo "$GTAG";
          echo "$URL";
          echo "$GREPO";
      - uses: actions/checkout@v2.3.4
        with:
          repository: $REPO
          ref: $TAG
        env:
          TAG: `echo $ARTIFACT | cut -d "/" -f 3`
          REPO: $(echo $URL | cut -d "/" -f 4-5)
      - run: ls