name: fetch-missing-jar-json
on: workflow_dispatch
jobs:
  list-files:
    runs-on: new-runner
    steps:
    - uses: actions/checkout@v2.3.4
    - run: gsutil -m rsync -i -r gs://project-step-pranav-hub-cdap-io/packages/ ./packages/
    - run: chmod +x ./.github/scripts/fetch.sh
    - run: ./.github/scripts/fetch.sh
    - id: set-matrix
      run: echo "::set-output name=matrix::${output}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-files:
    needs: list-files
    if: ${{ needs.list-files.outputs.matrix != '[]' && needs.list-files.outputs.matrix != '' }}
    runs-on: new-runner
    strategy:
      fail-fast: false
      matrix:
        artifact: ${{ fromJSON(needs.list-files.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repository: ${{ matrix.artifact.repo.checkout }}
          ref: ${{ matrix.artifact.repo.tag }}
      - run: mvn clean package -DskipTests
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact.artifact }}
          path: ${{ matrix.artifact.target_path }}

  merge-files:
    needs: build-files
    if: always()
    runs-on: new-runner
    steps:
      - uses: actions/checkout@v2.3.4
      - run: gsutil -m rsync -i -r gs://project-step-pranav-hub-cdap-io/packages/ ./packages/
      - uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - run: chmod +rwx ./.github/scripts/merge.sh
      - run: ./.github/scripts/merge.sh
