name: fetch-missing-jar-json
on: workflow_dispatch
jobs:
  list-files:
    runs-on: new-runner
    steps:
    - uses: actions/checkout@v2.3.4
    - run: chmod +x ./.github/scripts/fetch.sh
    - run: ./.github/scripts/fetch.sh
    - id: set-matrix
      run: echo "::set-output name=matrix::${output}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-files:
    needs: list-files
    runs-on: new-runner
    strategy:
      fail-fast: false
      matrix:
        artifact: ${{ fromJSON(needs.list-files.outputs.matrix) }}
    steps:
      - run: echo "${{ matrix.artifact.path }} - ${{ matrix.artifact.url }}"
      - run: ARTIFACT=${{ matrix.artifact.path }}
      - run: URL=`echo "${{ matrix.artifact.url }}" | cut -d "/" -f 4-5`
      - run: TAG=`echo "$ARTIFACT" | cut -d "/" -f 3`
      - run: |
          echo "$ARTIFACT";
          echo "$TAG";
          echo "$URL";
      - uses: actions/checkout@v2.3.4
        with:
          repository: $URL
          ref: $TAG
      - run: ls