name: fetch-missing-jar-json
on: workflow_dispatch
jobs:
  list-files:
    runs-on: new-runner
    steps:
      - uses: actions/checkout@v2.3.4
      - run: chmod +x ./.github/scripts/fetch.sh
      - run: ./.github/scripts/fetch.sh