name: fetch-missing-jar-json
on: workflow_dispatch
jobs:
  list-files:
    runs-on: new-runner
    steps:
    - uses: actions/checkout@v2.3.4
    - run: chmod +x ./.github/scripts/fetch.sh
    - run: ./.github/scripts/fetch.sh
    - id: set-matrix
      run: echo "::set-output name=matrix::${output}"
    - run: sudo rm -r ./
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-files:
    needs: list-files
    runs-on: new-runner
    strategy:
      matrix:
        artifact: ${{ fromJSON(needs.list-files.outputs.matrix) }}
    steps:
      - run: ARTIFACT=${{ matrix.artifact.path }}
      - uses: actions/checkout@v2.3.4
      - run: ls
      - run: TAG=`echo $ARTIFACT | cut -d "/" -f 3`
      - run: DIR=${ARTIFACT%/*}
      - run: URL="`jq -r '.actions[] | select(.type == "one_step_deploy_plugin").arguments[] | select(.name == "repo_url").value' \"${DIR}/spec.json\"`"
      - run: |
          echo $ARTIFACT;
          echo $TAG;
          echo $DIR;
          echo $URL;