name: fetch-missing-jar-json
on: workflow_dispatch
jobs:
  list-files:
    runs-on: new-runner
    steps:
    - uses: actions/checkout@v2.3.4
    - run: gsutil -m rsync -i -r gs://project-step-pranav-hub-cdap-io/packages/ ./packages/
    - run: chmod +x ./.github/scripts/fetch.sh
    - run: ./.github/scripts/fetch.sh
    - id: set-matrix
      run: echo "::set-output name=matrix::${output}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  fetch-files:
    needs: list-files
    if: ${{ needs.list-files.outputs.matrix != '[]' }}
    runs-on: new-runner
    strategy:
      fail-fast: false
      matrix:
        artifact: ${{ fromJSON(needs.list-files.outputs.matrix) }}
    env:
      ID: ${{ matrix.artifact.repo.id }}
      VERSION: ${{ matrix.artifact.repo.version }}
      EXTENSION: ${{ matrix.artifact.repo.file_type }}
    steps:
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:copy -Dartifact=${ID}:${VERSION}:${EXTENSION} -DoutputDirectory=./artifact/
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact.artifact }}
        path: ${{ matrix.artifact.target_path }}

  merge-files:
    needs: fetch-files
    if: always()
    runs-on: new-runner
    steps:
    - uses: actions/checkout@v2.3.4
    - run: gsutil -m rsync -i -r gs://project-step-pranav-hub-cdap-io/packages/ ./packages/
    - uses: actions/download-artifact@v3
      with:
        path: artifacts/
    - run: chmod +rwx ./.github/scripts/merge.sh
    - run: ./.github/scripts/merge.sh
    - run: gsutil -m rsync -r ./packages/ gs://project-step-pranav-hub-cdap-io/packages/
