name: fetch-missing-jar-json
on: workflow_dispatch
jobs:
  list-files:
    runs-on: new-runner
    steps:
      - uses: actions/checkout@v2.3.4
      - run: chmod +x ./.github/scripts/fetch.sh
      - run: ./.github/scripts/fetch.sh
      - id: set-matrix
        run: echo "::set-output name=matrix::${toFetch[@]}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-files:
    needs: list-files
    runs-on: new-runner
    strategy:
      matrix:
        artifact: ${{ needs.list-files.outputs.matrix }}
    steps:
      - run: echo ${{ matrix.artifact }}