name: test-and-debug
on: workflow_dispatch
jobs:
  strategy-matrx:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - run: echo "${{ matrix.os }}"
      - run: VAR=${{ matrix.os }}
      - run: VAL=`${{ matrix.os }} | cut -d "-" -f 2`
      - run: |
          echo $VAR;
          echo $VAL;
      - run: echo $OS;
      - run: OS_VAL=`echo $OS | cut -d "-" -f 2`
      - run: echo $OS_VAL;